In [1]:
import numpy as np
a=np.array([[0,1],[2,3],[4,5]])
b=np.array([[0,1,2,3],[4,5,6,7]])
result_matrix=np.dot(a,b)
max_value=np.max(result_matrix)

print(result_matrix)
print({max_value})


[[ 4  5  6  7]
 [12 17 22 27]
 [20 29 38 47]]
{47}
